# Generated by Django 4.1.2 on 2023-06-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Photo',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
