# Generated by Django 4.1.2 on 2023-06-07 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
